# Generated by Django 5.2.5 on 2025-10-08 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetaFinanceira',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_meta', models.CharField(max_length=100)),
                ('descricao_meta', models.TextField(blank=True)),
                ('valor_atual_meta', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('valor_objetivo_meta', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_criacao_meta', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
