# Generated by Django 5.2.5 on 2025-11-03 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_metafinanceira'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transacao',
            name='categoria',
            field=models.CharField(choices=[('alimentacao', 'Alimentação'), ('lazer', 'Lazer'), ('transporte', 'Transporte'), ('contas_casa', 'Contas de Casa'), ('trabalho', 'Trabalho'), ('estudo', 'Estudo'), ('outro', 'Outro')], max_length=20),
        ),
    ]
