# Generated by Django 5.2.5 on 2025-11-05 19:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_alter_transacao_categoria'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MetaOrcamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(choices=[('alimentacao', 'Alimentação'), ('lazer', 'Lazer'), ('transporte', 'Transporte'), ('contas_casa', 'Contas de Casa'), ('trabalho', 'Trabalho'), ('estudo', 'Estudo'), ('outro', 'Outro')], max_length=20)),
                ('limite_mensal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('mes_ano', models.DateField(default=models.DateField(auto_now_add=True))),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Meta de Orçamento',
                'verbose_name_plural': 'Metas de Orçamento',
                'unique_together': {('user', 'categoria', 'mes_ano')},
            },
        ),
    ]
